### PR TITLE
Fix/update readme

### PR DESCRIPTION
**Pull request by daveRanjan**

### CODE REVIEW

**Review by monis01 — COMMENTED** [review]
Do we still need bootstrap cdn, after adding nom package?
If its only css, we can add that inside angular.json styles array...

**Review by monis01 — COMMENTED** [review]
Please check typo in readme, for naming i.e. Stomper or Stopmer.

**Review by monis01 — CHANGES_REQUESTED** [review]
Please check requested changes

**Comment by daveRanjan** [comment]
> Please check typo in readme, for naming i.e. Stomper or Stopmer.

fixed typo

**Comment by daveRanjan** [comment]
> Do we still need bootstrap cdn, after adding nom package? If its only css, we can add that inside angular.json styles array...

Yes, it was in the steps.

**Review by monis01 — APPROVED** [review]

**Comment by monis01** [comment]
Approved

**Pull request merged**
